version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=salineantitoxin256
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    networks:
      - br_internal
    restart: always
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
    container_name: codimd
    environment:
      - CMD_DB_URL=postgres://codimd:salineantitoxin256@database/codimd
      - CMD_USECDN=false

      # to keep the data stored in codimd private from any wanderers on the internet
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_EMAIL_REGISTER=false

      # these settings are only used to generate correct hyperlinks
      # https is handled by NGINX, codimd is still using HTTP
      - CMD_DOMAIN=md.jinx.systems
      - CMD_PROTOCOL_USESSL=true
    depends_on:
      - database
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    networks:
      - br_internal
      - proxy
    restart: always
# used to store persistent data
volumes:
  database-data: {}
  upload-data: {}
networks:
  # for private communication between codimd and the database
  br_internal:
    driver: bridge
    # disable internet access
    internal: true
  # network to connect with NGINX
  proxy:
    external:
      name: br_codimd

