version: "3"
services:
  npm_build:
    build:
      context: ../../
      dockerfile: src/frontend/Dockerfile.frontend.deploy
    volumes:
      # directly deploy the built files
      - "/srv/www/frontend:/build"
