version: '3'
services:
  npm_build:
    build:
      context: ../../
      dockerfile: Dockerfile.frontend.deploy
    volumes:
      # directly deploy the built files
      - "/srv/www/frontend:/code/build"
